version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  ApplicationStop:
    - location: appStop.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 30
      runas: root
  Install:
    - location: install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
